import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Layout, Menu, Breadcrumb } from 'antd';
import React, { useEffect, useState } from "react";

import Button from 'react-bootstrap/Button'
import Navbar from 'react-bootstrap/Navbar'
import Nav from 'react-bootstrap/Nav'
import Container from 'react-bootstrap/Container'
import HeroSection from '../Components/herosection.js'

const { Header, Footer, Sider, Content } = Layout;
// Homepage here
function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>eVote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossOrigin="anonymous"/>
        <link rel="icon" href="/evote-favicon.svg" />
      </Head>

      <Navbar>
        <Container>
        <Navbar.Brand href="/">
          <img src="/evote-icon.svg" alt="Evote Logo" width="160px" height="160px" style={{marginLeft:"60px", marginRight:"60px"}}/>
        </Navbar.Brand>
        <Nav className="me-auto">
          <Navbar.Text style={{marginLeft:"60px", marginRight:"60px", marginTop:"8px", fontSize:25}}>
            <Nav.Link href="/">Home</Nav.Link>
          </Navbar.Text>
          <Navbar.Text style={{marginLeft:"60px", marginRight:"60px", marginTop:"8px", fontSize:25}}>
            <Nav.Link href="/election_results">Election Results</Nav.Link>
          </Navbar.Text>
          <Nav.Link href="/sign_in">
            <Button variant="success" style={{marginLeft:"60px", marginRight:"60px"}}><Navbar.Text style={{fontSize:25, marginLeft:"20px", marginRight:"20px", color:"#eaeaea"}}>Vote Now</Navbar.Text></Button>{' '}
          </Nav.Link>
        </Nav>
        </Container>
      </Navbar>

    <HeroSection />

      <footer className={styles.footer}>
        <a href="#" target="_blank" rel="noopener noreferrer">
          Copyright 2021 Evote <br />
        </a>
      </footer>
    </div>
  )
}
export default Home
