import Head from 'next/head';
import styles from '../styles/Home.module.css';



export default function LoginPage(){
    const informationHandoff = async(event) => {
        event.preventDefault();
        const ssn = event.target[0].value
        const firstname = event.target[1].value
        const lastname = event.target[2].value
        const birthday = event.target[3].value
        const street_address = event.target[4].value
        const zip_code = parseInt(event.target[5].value);
        const state = event.target[6].value
        console.log(ssn)
        const resp = await fetch("/api/auth/sign_in", {
            method: "POST",
            body: JSON.stringify({
                ssn: ssn,
                firstname: firstname,
                lastname: lastname,
                birthday: birthday,
                street_address: street_address,
                zip_code: zip_code,
                state: state
            })
        })
        console.log(await resp.text())
    }
    return(
        <div className={styles.container}>
            <Head>
                <title>Verify Your Information</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossOrigin="anonymous"/>
                <link rel="icon" href="/evote-favicon.svg" />
        </Head>
        <main className = {styles.main}>
            <form onSubmit={informationHandoff} id="form_data">
                Enter your Social Security Number: <input type="text" id = "ssn"/>
                <p></p>
                Enter your first name: <input type="text" />
                <p></p>
                Enter your last name: <input type="text" />
                <p></p>
                <p></p>
                Enter your Date of Birth (mm/dd/yyyy): <input type="text" />
                <p></p>
                Enter your Street Address: <input type="text" />
                <p></p>
                Enter your Zip Code: <input type="text" />
                <p></p>
                Enter your State: <input type="text" />
                <p></p>
                <button type="submit">Submit</button>
            </form>
        </main>
      </div>
    )
}