// Near private key is (comment is meant for vidur): sponsor void history sample recall soldier pet panel cotton paper enjoy decline 
// DO NOT DELETE ABOVE COMMENT UNTIL PRIVATE KEY IS USED

import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Vote(){
    return(
        <Head>
            <title>Cast your vote!</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}