// Near private key is (comment is meant for vidur): sponsor void history sample recall soldier pet panel cotton paper enjoy decline 
// DO NOT DELETE ABOVE COMMENT UNTIL PRIVATE KEY IS USED

import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Card from 'react-bootstrap/Card'
import Button from 'react-bootstrap/Button'

export default function Vote(){
    return(
        <div className={styles.container}>
        <Head>
            <title>eVote</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/evote-favicon.svg" />
        </Head>

        <footer className={styles.footer}>
        <a href="#" target="_blank" rel="noopener noreferrer">
          Copyright 2021 Evote <br />
        </a>
        {/* TODO I want to add the logo below the copyright but it's adding to the side*/}
        {/* <img src="evote-icon.svg" alt="Evote Logo" width="128px" height="128px" /> */}
        </footer>

        </div>
    )
}