import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Button from 'react-bootstrap/Button'
import Navbar from 'react-bootstrap/Navbar'
import Nav from 'react-bootstrap/Nav'
import Container from 'react-bootstrap/Container'
import Card from 'react-bootstrap/Card'
import Placeholder from 'react-bootstrap/Placeholder'
import Alert from 'react-bootstrap/Alert'
import ProgressBar from 'react-bootstrap/ProgressBar'
import Badge from 'react-bootstrap/Badge'
import Toast from 'react-bootstrap/Toast'
import ToastHeader from 'react-bootstrap/ToastHeader'
import ToastBody from 'react-bootstrap/ToastBody'
import ToastContainer from 'react-bootstrap/ToastContainer'

export default function VotingDummy(){
    return(
        <div className={styles.container}>
        <Head>
            <title>Vote</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossOrigin="anonymous"/>
            <link rel="icon" href="/evote-favicon.svg" />
        </Head>

        <Navbar>
        <Container>
        <Navbar.Brand href="/">
          <img src="/evote-icon.svg" alt="Evote Logo" width="160px" height="160px" style={{marginLeft:"60px", marginRight:"60px"}}/>
        </Navbar.Brand>
        <Nav className="me-auto">
          <Navbar.Text style={{marginLeft:"60px", marginRight:"60px", marginTop:"8px", fontSize:25}}>
            <Nav.Link href="/">Home</Nav.Link>
          </Navbar.Text>
          <Navbar.Text style={{marginLeft:"60px", marginRight:"60px", marginTop:"8px", fontSize:25}}>
            <Nav.Link href="/election_results">Election Results</Nav.Link>
          </Navbar.Text>
          <Nav.Link href="/sign_in">
            <Button variant="success" style={{marginLeft:"60px", marginRight:"60px"}}><Navbar.Text style={{fontSize:25, marginLeft:"20px", marginRight:"20px", color:"#eaeaea"}}>Vote Now</Navbar.Text></Button>{' '}
          </Nav.Link>
        </Nav>
        </Container>
      </Navbar>
            <div>
            

            <h1 className="text-center">Vote</h1>
            <br/>
            <br/>
                
            
            </div>
            <div className={styles.app}>
            <div className={styles.questionsection}>
                <div className={styles.questiontext}>
                    <h2 className="text-center">Position</h2>
                </div>
            </div>
            <br/>
            <div className={styles.answersection}>
            <Card bg="light" style={{ width: "10rem", float:"left", marginRight:"50px"}}>
                    <Card.Img variant="top" src="http://stillmotion.com/wp-content/uploads/2016/12/C_Glisson-1.jpg?0dba88&0dba88" />
                    <Card.Body>
                        <Card.Title className="text-center">Candidate 1</Card.Title>
                    </Card.Body>
                    <Button href="/votingconfirmation" variant="success" size="lg">Vote</Button>
                </Card>
            
                <Card bg="light" style={{ width: "10rem", float:"left", marginRight:"50px"}}>
                    <Card.Img variant="top" src="https://images.squarespace-cdn.com/content/v1/51ef4493e4b0561c90fa76d6/1538426393436-K1MYAHN7VT68NEQ0G529/Business+Headshot.jpg" />
                    <Card.Body>
                        <Card.Title className="text-center">Candidate 2</Card.Title>
                    </Card.Body>
                    <Button href="/votingconfirmation" variant="success" size="lg">Vote</Button>
                </Card>

                <Card bg="light" style={{ width: "10rem" }}>
                    <Card.Img variant="top" src="https://www.christophergrey.com/wp-content/uploads/2020/10/Twin-Cities-female-business-headshot-sq.jpg" />
                    <Card.Body>
                        <Card.Title className="text-center">Candidate 3</Card.Title>
                    </Card.Body>
                    <Button href="/votingconfirmation" variant="success" size="lg">Vote</Button>
                </Card>

            </div>
            
            
            
            </div>
            <br/>
            <br/>
            <br/>

        <footer className={styles.footer}>
            <a href="#" target="_blank" rel="noopener noreferrer">
            Copyright 2021 Evote <br />
            </a>
            {/* TODO I want to add the logo below the copyright but it's adding to the side*/}
            {/* <img src="evote-icon.svg" alt="Evote Logo" width="128px" height="128px" /> */}
        </footer>
        </div>
    )
}